#!/bin/bash

#convert css to scss  https://css2sass.herokuapp.com/

echo 
echo "usage:  ./build ---> one time build all scss files "
echo "usage:  ./build watch ---> monitor all scss files and compile modified "
echo 

if [ "$1" == "watch" ]; then
    echo "WATCH"
    sass --watch styles.scss:../styles.css colors.scss:../colors.css

else 

    echo -n "build styles.css"
    sass styles.scss ../styles.css
    echo " - done"

    echo -n "build colors.css"
    sass colors.scss ../colors.css
    echo " - done"

fi

echo 
echo "build done."
echo